#
#    ░██████╗████████╗██╗████████╗██╗░░░██╗██╗░░░░░
#    ██╔════╝╚══██╔══╝██║╚══██╔══╝██║░░░██║██║░░░░░
#    ╚█████╗░░░░██║░░░██║░░░██║░░░██║░░░██║██║░░░░░
#    ░╚═══██╗░░░██║░░░██║░░░██║░░░██║░░░██║██║░░░░░
#    ██████╔╝░░░██║░░░██║░░░██║░░░╚██████╔╝███████╗
#    ╚═════╝░░░░╚═╝░░░╚═╝░░░╚═╝░░░░╚═════╝░╚══════╝

#     OWNER: skully | SITE: https://skully.space


messages:
  none: "Титул пуст"
  remove: "Титул удален"
  set: "Титул установлен"
  help:
    - "/settitul titul"