#
#    ░██████╗████████╗██╗████████╗██╗░░░██╗██╗░░░░░
#    ██╔════╝╚══██╔══╝██║╚══██╔══╝██║░░░██║██║░░░░░
#    ╚█████╗░░░░██║░░░██║░░░██║░░░██║░░░██║██║░░░░░
#    ░╚═══██╗░░░██║░░░██║░░░██║░░░██║░░░██║██║░░░░░
#    ██████╔╝░░░██║░░░██║░░░██║░░░╚██████╔╝███████╗
#    ╚═════╝░░░░╚═╝░░░╚═╝░░░╚═╝░░░░╚═════╝░╚══════╝

#     OWNER: skully | SITE: https://skully.space

name: STitul
version: '${project.version}'
main: me.skully.titul.Main
authors: [ skully ]
website: skully.space
commands:
  settitul: